# Generated by Django 4.2.5 on 2023-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_todo_time_todo_date_todo_hour_todo_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
