# Generated by Django 4.2.7 on 2023-11-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_history_device_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
        ),
    ]
